apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-9wg99
      readOnly: true
    env:
    - name: DB_Host
      valueFrom:
         secretKeyRef:
            name: db-secret
            key: DB_Host
    - name: DB_User
      valueFrom:
         secretKeyRef:
            name: db-secret
            key: DB_user
    - name: DB_Password
      valueFrom:
          secretKeyRef:
             name: db-secret
             key: DB_Password
