apiVersion: v1
kind: Binding 
metadata:
    name: nginx
target:
    apiVersion: v1
    kind: Node
    name: <Node Name> 
    # curl --header "Content-Type:application/json" --request POST --data '{"apiVersion":"v1","kind":"Binding ..}' http://server/api/v1/namespace/default/pods/podname/binding  
