apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp 
    type: front-end
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-container 
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"    
    effect: "NoSchedule" # PreferNoSchedule , NoExecute 

