apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXR5KzlDcVdmUStPQXdmbWhoYzRzZmxTS1RoYzlkell5eGtRRGxsTEVUTzY4CldvbVVGaFF2NFpNaWUvNzdFOFIvS1NGTEE4QXVSajlqT2dUTEY0S1NGSDlGQXpobUFxQXhrUVN2UHFTUGNyRlIKTjF1NzZJVkRhcHJLVldEUWlhYWVFTTJLQzdyMURUVnRIODdPL1BNckN1Vng5SE9DaXpuQmhoVzk3TkVBM05xbgpNT0twQzlkelE5STBQNVN4dDliL0QrZzFwS2FmSDQ4RXY1UldzQ1dKbWh3QW5iV09SR0Zhdzk5cmZyOERhZGFvCjIwTEJRMWIrcmQ1aG9RcmF4dGZjdlhpQ05wdGN0dlBnak12bUt6ZEl3MXV2TzFCWi9KYzBpRFZiTjE2ZHkwYncKOUNiblAxVDBIaTlQWU1XOHJaTGtnVFlSUVREOHYvcGxjc0hZbnpualZ3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQ1RvZHVSVTNWbHdOM2V5c21SSG53enVUZ0lDb1NtUDI3TEtoYXJ3NHVEV0FYalNFcFlkCnYxNFdhbEtsWHVtMGw5eWVUeUFIQXU5WHlXSXd2WjdDbWFkamh6V3R2c1k0ZThDQXFMSE1FOVlGTm1kcTNycVUKRkRKQUNHaGJ4MU1Pd2gvcm5kMUllQ00xNWl5MytDRC9aZHBNKy9jQnhmOGdtMndPeUtMQzV3dit2RDhoZDJvRQowaUMzWDhyTG9CSC9xakFBU2taN0dUYzZ6dGhGRGt6bEwxbkZ3OVpxYTNQM1JRU2JPZHFDbVlha2lMNFRBVHBvCnBWQUNDVnVIZkNLM01uV2hJdHcrNGx1SDBseHd0cHpqTjlDRVM1em5wVjJBMDZ4c0ZqSHN1Q29DbmdVUzZ1Y3MKeUlsSUlCUDNhcUhCTEpIMXZ0ZzlIWWJJQ1BwYXNVQk1iUDQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
